services:
  postgres:
    image: postgres:15-alpine
    ports:
      - '5432:5432'
    command: -c shared_buffers=500MB -c fsync=off
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-pg}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-pg}
      POSTGRES_DB: ${POSTGRES_DB:-}
